[package]
name = "fibonacci"
version = "0.1.0"
authors = ["housian <sianhou1987@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "0.4.0"

[profile.release]
lto = true
debug = 1
